### ISSUE TITLE
Non-installer version

### ISSUE THREAD

**Issue by vrubayka** [megakarlach/HL2reUpdate#4]
Please provide an archive with just the files that should overwrite the vanilla HL2 Update.

**Comment by megakarlach** [comment]
For now, it's located on GitHub code page, just click on code > Download ZIP, but I will work on it later soon.

**Comment by megakarlach** [comment]
Edit:  [v1.0.4.2](https://github.com/megakarlach/HL2reUpdate/releases/tag/v1.0.4.2) (Windows) has the non-Installer version now.
